### ISSUE TITLE
The server didn't respond in time.?

### ISSUE THREAD

**Issue by watchpoints** [JoneXiong/YouMd#1]
when  I run  python server.py i get  the message：
Mole server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:8081/

uname -a
Linux localhost 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
sestatus
1  SELinux status:                 disabled

But  i  cannot visit from window 
504 Gateway Time-out

The server didn't respond in time.
why

**Comment by JoneXiong** [comment]
Which version of python did u use？
vim server.py 
0.0.0.0  8081 change them

**Comment by izuolan** [comment]
File path to full English，It work～～

**Comment by JoneXiong** [comment]
awesome！
