### ISSUE TITLE
使用中发现的几个问题

### ISSUE THREAD

**Issue by zwgshr** [JoneXiong/YouMd#10]
1、在编辑器中无法直接退出到内容页或首页（不方便）
2、发布时如果指定文件名是中文时报错，在代码中将文件名转为utf-8后解决（win10旗舰版+Python2.7.11）
3、在编辑器中编辑过一次后，点击编辑器想新建一个文档，结果自动带出了上一次的编辑内容。

**Comment by JoneXiong** [comment]
@zwgshr 感谢反馈，会尽快做对应改善

**Comment by daizhan** [comment]
@JoneXiong  让我来看看。
