### ISSUE TITLE
建议编辑器链接在新页面打开

### ISSUE THREAD

**Issue by shenjinxi** [JoneXiong/YouMd#6]
编辑器链接现在是在当前页面打开的，而且没有返回首页的链接，操作不方便。
建议新建一个页面打开或在编辑器页面提供返回首页的链接。

**Comment by JoneXiong** [comment]
好建议！欢迎提Pull requests

**Comment by JoneXiong** [comment]
已合并提的 requests，赞一个！以后一起做好这个开源项目
